service_name: verse_sequel_specs_sqlite
description: Testing of the Sequel SQLite implementation.

logging:
  level: warn
em:
  adapter: local
plugins:
  - name: sequel
    config:
      mode: simple
      db:
        uri: sqlite://tmp/test.sqlite?max_connections=1