service_name: verse_sequel_specs_sqlite
description: Testing of the Sequel SQLite implementation.

logging:
  level: warn
em:
  adapter: local
plugins:
  - name: sequel
    config:
      mode: cluster
      extensions:
        - pg_json
        - pg_array
      master:
        uri: postgres://postgres@localhost:5432/verse_sequel_test
      replica:
        uri: postgres://postgres@localhost:5432/verse_sequel_test